kind: Service
apiVersion: v1
metadata:
  name: cats-and-dogs-frontend
spec:
  selector:
    app: cats-and-dogs-frontend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30200
  type: NodePort
