apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: c2cnetworking/proxy
          ports:
            - containerPort: 8080
